name: Docker image build and push

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "push" ]; then
          VERSION=${GITHUB_REF_NAME#v}
        else
          VERSION=${{ inputs.version }}
        fi
        echo "version=${VERSION}" >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/arm64,linux/amd64
        tags: |
          ${{ vars.DOCKERHUB_USERNAME }}/ha-sgcc-sensor:latest
          ${{ vars.DOCKERHUB_USERNAME }}/ha-sgcc-sensor:${{ steps.version.outputs.version }}
